<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Total_product_image</name>
   <tag></tag>
   <elementGuidId>d8261b9f-282b-4f2d-b77a-aa010e99a01e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='product-2']/td/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.product_image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>937365b1-958b-47b1-8840-d408af45fa72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>get_product_picture/2</value>
      <webElementGuid>05e62b4b-3c15-406d-88d0-4952032d7130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product_image</value>
      <webElementGuid>510245a3-611e-41ea-99be-4e6d7d755c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Product Image</value>
      <webElementGuid>049680fe-87b9-400c-9fef-95a2b45833a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-2&quot;)/td[@class=&quot;cart_product&quot;]/a[1]/img[@class=&quot;product_image&quot;]</value>
      <webElementGuid>2cdd6483-cff1-4a74-848a-6b416195eda8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='product-2']/td/a/img</value>
      <webElementGuid>edfdd510-5a0b-4aef-9580-c2a6c777c260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Product Image']</value>
      <webElementGuid>cd7bddc0-868b-40ae-b5c2-d67d5fd1dfc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a/img</value>
      <webElementGuid>a98f63d6-27a3-4971-9b7d-028aeaa8d93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'get_product_picture/2' and @alt = 'Product Image']</value>
      <webElementGuid>0b41da1f-10ee-4791-ad35-696a6f7847df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
