<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Address2</name>
   <tag></tag>
   <elementGuidId>42a2721b-491e-471b-be50-77d0ca306c5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b30db55-c293-4761-a66e-88cbf62103d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05cca245-84f6-404c-924f-17ffdf304c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>address2</value>
      <webElementGuid>94ca4163-b74a-49ae-8806-dab03c4d3da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f2b37f12-1469-4928-85ce-67cd76448ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address2</value>
      <webElementGuid>f2c08727-5081-4aaa-9998-69c9684579e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address2</value>
      <webElementGuid>0a07d40b-244c-4459-9096-d6c08b2e615a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address2&quot;)</value>
      <webElementGuid>cf3117af-371c-4eb0-87aa-5bbd9bc34948</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address2']</value>
      <webElementGuid>c902d017-034d-425f-a390-5f41d662a5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='form']/div/div/div/div/form/p[5]/input</value>
      <webElementGuid>ed55ad54-3199-4745-9725-faa0d2607ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/input</value>
      <webElementGuid>3bf095fe-fd18-4e29-8713-cef4cc33af40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address2' and @id = 'address2']</value>
      <webElementGuid>04b2c1e7-827f-4b53-8e19-35b359bf4600</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
