<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Street address, P.O. Box, Company na_957d3e</name>
   <tag></tag>
   <elementGuidId>64c61193-ea79-4db3-a55d-822bf43f2037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d99c712-0f0a-4f06-a60b-6f2bfd5feed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8380054-11c9-4ba1-9f2b-2a9fe4edd2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>f10fa5d9-609a-405a-b387-186816e45952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1e8e42c1-c649-432f-87d3-49920394420a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address1</value>
      <webElementGuid>af1937e7-3880-4e7b-a913-6858bb7f3766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address1</value>
      <webElementGuid>5337263c-09ec-4cae-85eb-1bf7824cef5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address1&quot;)</value>
      <webElementGuid>a55929f4-72b6-4381-a4f1-b906a95b13e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address1']</value>
      <webElementGuid>54aac898-c12b-492e-a939-85039dcd5bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='form']/div/div/div/div/form/p[4]/input</value>
      <webElementGuid>9fcec1d7-8302-4e67-b6a1-4c828bfe319e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/input</value>
      <webElementGuid>96945416-ceef-41f1-b624-e732b08cb2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address1' and @id = 'address1']</value>
      <webElementGuid>3e42b7ab-25bc-4e63-8332-bb378f8d5cb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
