<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Category_Tshirt</name>
   <tag></tag>
   <elementGuidId>6c03e531-f99b-4321-a39d-5f3b2c48b7e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Men > div.panel-body > ul > li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Men']/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>420900f5-16be-4c96-b688-2f976f10ebb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tshirts </value>
      <webElementGuid>c2025811-a9b6-4f65-98ba-1140e12d96d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Men&quot;)/div[@class=&quot;panel-body&quot;]/ul[1]/li[1]</value>
      <webElementGuid>30d9b751-fdbc-4ffe-9e06-e6a007bdeb96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Men']/div/ul/li</value>
      <webElementGuid>823c8d8b-44ed-41f5-9733-e3590e7aa96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saree'])[1]/following::li[1]</value>
      <webElementGuid>6c562a35-f91c-4fc7-ac69-3fe19de430bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jeans'])[1]/preceding::li[1]</value>
      <webElementGuid>d0580496-c5e6-46fa-8972-a7963e1d4dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/ul/li</value>
      <webElementGuid>25c154b8-ac30-49e9-b4ff-690bec068c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Tshirts ' or . = 'Tshirts ')]</value>
      <webElementGuid>6213d21b-8b0a-42c7-bc1a-85111c83973e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
