<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Account_Created</name>
   <tag></tag>
   <elementGuidId>3da0fd68-a015-4c48-95fa-eefb1aede31e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#optin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='optin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0c75932-4c16-4ea9-ad66-1d9bde17a9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5ac86982-6a96-434e-a377-69cb61b897c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optin</value>
      <webElementGuid>c15526b0-549a-40d2-8f9c-8405c1b09334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optin</value>
      <webElementGuid>a4ca647a-df73-4153-b58f-5ae2cf3f3e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>19ac92eb-535f-46e7-a569-cab44068ed3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optin&quot;)</value>
      <webElementGuid>e035fe3d-bb8f-48ff-af6f-7cee85e638f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='optin']</value>
      <webElementGuid>1ab4e236-e2b8-49a2-815c-ffe8de70ca7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-optin']/span/input</value>
      <webElementGuid>13ae5a77-0b96-4192-bbf7-757f7949efd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/span/input</value>
      <webElementGuid>24799504-e98c-4a11-bbb0-12cb5146fc01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'optin' and @id = 'optin']</value>
      <webElementGuid>4186ac92-ec4c-482d-906b-8b12a51c329a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
