<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Category_Tops</name>
   <tag></tag>
   <elementGuidId>1089821c-1f98-458a-8b2e-e7de9f20e3d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Kids > div.panel-body > ul > li:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Kids']/div/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>777929e4-b68b-4c9c-90a3-6a08354d85f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tops &amp; Shirts </value>
      <webElementGuid>005ad375-8fb9-49e5-91ee-63c7b70ca007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kids&quot;)/div[@class=&quot;panel-body&quot;]/ul[1]/li[2]</value>
      <webElementGuid>db45147f-8023-46f4-993a-39153bce3eea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Kids']/div/ul/li[2]</value>
      <webElementGuid>de86ae7f-c1f9-48cf-ba77-32f6032758bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dress'])[2]/following::li[1]</value>
      <webElementGuid>945d15d2-4b4e-4ca9-aebd-37c5143ed376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brands'])[1]/preceding::li[1]</value>
      <webElementGuid>9ce852c1-f3c3-4922-bce4-14332e8acc1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/ul/li[2]</value>
      <webElementGuid>4920044c-4eac-438f-82ba-494784b87cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Tops &amp; Shirts ' or . = 'Tops &amp; Shirts ')]</value>
      <webElementGuid>1874f7fd-2b0a-4708-bb65-036983e34a3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
